services:
  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:latest
    command: server start
    volumes:
      - atuin:/config
    networks:
      - webnet
      - internal
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@postgresql/atuin
    depends_on:
      - postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atuin.rule=Host(`atuin.niklas.ai`)"
      - "traefik.http.routers.atuin.entrypoints=websecure,websecure-internal"
      - "traefik.http.routers.atuin.tls.certresolver=myresolver"
      - "traefik.docker.network=webnet"
      - "traefik.http.services.atuin.loadbalancer.server.port=8888"

  postgresql:
    image: docker.io/postgres:14-alpine
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: $ATUIN_DB_USERNAME
      POSTGRES_PASSWORD: $ATUIN_DB_PASSWORD
      POSTGRES_DB: atuin
    networks:
      - internal

volumes:
  db:
  atuin:

networks:
  webnet:
    external: true
  internal: {}
